# Generated by Django 5.1 on 2024-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=240)),
                ('serialnumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=256)),
                ('pcmodel', models.CharField(max_length=256)),
                ('processor', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('rom', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
