# Generated by Django 5.1 on 2024-09-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='amount',
            field=models.CharField(default=10000, max_length=30),
            preserve_default=False,
        ),
    ]
